# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e09691dcab4a3545114f530dded885f1b0b0dc09b447c01a6ef6483fc64ead68de6b4e0a14b2545d09810a8efcdc712bfe7beed658c06298df5814e5d124677

test:
  secret_key_base: c2f4cbb3cc2e7c8c2dfbbf0c4ad18dbee4a035e194b7de80512a151399d702a42ecaca5b30b1c2a29b0c2eb9565d05a1bed6cbcd9201bd5f874f01dd129e8eba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
